dist: trusty
language: c
addons:
  apt:
    sources:
      - sourceline: ppa:team-gcc-arm-embedded/ppa
    packages:
      - gcc-arm-embedded
script:
  - make release OUT=bcf-radio-power-controller-rgbw144-${TRAVIS_TAG} VERSION=${TRAVIS_TAG} LED_STRIP_COUNT=144 LED_STRIP_TYPE=4
  - make release OUT=bcf-radio-power-controller-rgbw72-${TRAVIS_TAG} VERSION=${TRAVIS_TAG} LED_STRIP_COUNT=72 LED_STRIP_TYPE=4
  - make release OUT=bcf-radio-power-controller-rgbw36-${TRAVIS_TAG} VERSION=${TRAVIS_TAG} LED_STRIP_COUNT=36 LED_STRIP_TYPE=4
  - make release OUT=bcf-radio-power-controller-rgb150-${TRAVIS_TAG} VERSION=${TRAVIS_TAG} LED_STRIP_COUNT=150 LED_STRIP_TYPE=3
deploy:
  skip_cleanup: true
  file_glob: true
  file: out/release/*.bin
  api_key: ${GITHUB_KEY}
  provider: releases
  overwrite: true
  on:
    tags: true
