article: https://www.hackster.io/154024/bigclown-smart-doorbell-398f3d
articles:
  - title: BigClown Smart Doorbell
    url: https://www.hackster.io/154024/bigclown-smart-doorbell-398f3d
    description: I work a lot in my garage or in the garden, so it happens pretty often that I just don't hear my doorbell. So I made a smart one.
    images:
      - url: https://hackster.imgix.net/uploads/attachments/888469/zvonek_(1)_lPQAZYvNmV.png?auto=compress%2Cformat&w=900&h=675&fit=min
assembly:
  - name: BigClown Button Module
  - name: BigClown Relay Module
  - name: BigClown Core Module
  - name: BigClown Mini Battery Module
